server:
  port: 8081

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/EmployeeDB?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Driver Class
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySQL Dialect
        format_sql: true
        default_schema: EmployeeDB
  config:
    import: "optional:configserver:http://localhost:9002"
  cloud:
    config:
      name: employee
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/